name: jpeg12
description: Load and display 12-bit JPEGs with support for windowing
repository: https://github.com/tvh/flutter-jpeg12
version: 0.1.0

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: '>=3.7.0'

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.0.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  ffigen: ^7.2.5

flutter:
  plugin:
    platforms:
      android:
        package: com.example.jpeg12
        pluginClass: Jpeg12Plugin
      ios:
        pluginClass: Jpeg12Plugin

ffigen:
  name: Jpeg12Native
  description: 'Bindings to the namespaced libjpeg 12-bit'
  output: 'lib/generated_bindings.dart'
  headers:
    entry-points:
      - 'ios/jpeg-9/jpeglib.h'
  llvm-path:
    - '/opt/homebrew/opt/llvm'
