name: libjpeg12
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  ffi: ^1.1.2

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  ffigen: ^4.1.3

flutter:
  plugin:
    platforms:
      android:
        package: com.example.libjpeg12
        pluginClass: Libjpeg12Plugin
      ios:
        pluginClass: Libjpeg12Plugin

ffigen:
  output: 'lib/generated_bindings.dart'
  headers:
    entry-points:
      - 'jpeg-9/jpeglib.h'
  llvm-path:
    - '/opt/homebrew/opt/llvm'
