name: jpeg12
description: Load and display 12-bit JPEGs with support fow windowing
version: 0.1.0

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  ffi: ^1.1.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  ffigen: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.jpeg12
        pluginClass: Jpeg12Plugin
      ios:
        pluginClass: Jpeg12Plugin

ffigen:
  name: Jpeg12Native
  description: 'Bindings to the namespaced libjpeg 12-bit'
  output: 'lib/generated_bindings.dart'
  headers:
    entry-points:
      - 'ios/jpeg-9/jpeglib.h'
  llvm-path:
    - '/opt/homebrew/opt/llvm'
